# Generated by Django 5.1 on 2025-06-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Media',
        ),
        migrations.DeleteModel(
            name='ImageProject',
        ),
    ]
