# Generated by Django 5.1 on 2025-06-25 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_alter_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='project',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='portfolio_app.projects'),
        ),
    ]
