# Generated by Django 5.1 on 2025-06-30 08:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_alter_media_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tecnlogies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
