# Generated by Django 5.1 on 2025-06-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_projects_tecnlogies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='tecnlogies',
            new_name='tecnologies',
        ),
    ]
