# Generated by Django 5.1 on 2025-08-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_rename_tecnlogies_projects_tecnologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(default='', max_length=800),
        ),
    ]
