# Generated by Django 5.1 on 2025-08-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_projects_link_alter_education_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='link',
        ),
        migrations.AddField(
            model_name='projects',
            name='link_back',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='link_front',
            field=models.URLField(default=''),
        ),
    ]
