# Generated by Django 5.1 on 2025-08-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_remove_projects_link_projects_link_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('sidebar', 'Sidebar'), ('presentation', 'Presentation'), ('skills', 'Skills'), ('projects', 'Projects'), ('education', 'Education')], max_length=200)),
                ('title_section', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.JSONField()),
                ('button_text', models.CharField(max_length=200)),
            ],
        ),
    ]
