# Generated by Django 5.1 on 2025-08-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_sectiontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontext',
            name='button_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sectiontext',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectiontext',
            name='section',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('presentation', 'Presentation'), ('skills', 'Skills'), ('projects', 'Projects'), ('education', 'Education')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sectiontext',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sectiontext',
            name='title_section',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
