# Generated by Django 5.1 on 2025-08-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_alter_sectiontext_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontext',
            name='section',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('presentation', 'Presentation'), ('skills', 'Skills'), ('soft_skills', 'Soft Skills'), ('contact', 'Contact')], max_length=200, null=True),
        ),
    ]
