# Generated by Django 5.1 on 2025-08-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0014_alter_sectiontext_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectiontext',
            old_name='section',
            new_name='section_text',
        ),
    ]
