# Generated by Django 5.1 on 2025-08-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0015_rename_section_sectiontext_section_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
